[copyright]
fix = true
default_year = "2026"
author = "Marcus Gigandet"
license = "gpl"
exclude = ["^vendor/"]

[licenses.gpl]
text = """
Copyright (C) {years} {author}

SPDX-License-Identifier: GPL-3.0-or-later
"""

[languages.asm]
extensions = [".S"]
block_start = "/* "
line_prefix = " * "
block_end = " */"

[languages.ada]
extensions = [".ads", ".adb", ".gpr"]
block_start = "-- "
line_prefix = "-- "
block_end = "-- "